[package]
name = "tailor"
version = "0.1.0"
authors = ["Petr Hodina <hodinapetr46@gmail.com>"]

[dependencies]
clap = "2.31.2"
serde = "1.0.41"
serde_derive = "1.0.41"
serde-xml-rs = "0.2.1"
generator = { path = "../generator"}
error-chain = "0.11.0"
